# Generated by Django 5.1.2 on 2024-12-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2jkIKkkOoCoAwxGGU9_qw0zZEfP8lshgO3Q&s', max_length=500),
        ),
    ]
