# Generated by Django 5.1.2 on 2024-12-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://images.jdmagicbox.com/comp/darjeeling/h1/9999px354.x354.181016125224.y3h1/catalogue/random-fast-food-pedong-darjeeling-fast-food-b66reu0l8c-250.jpg', max_length=500),
        ),
    ]
