# Generated by Django 5.1.2 on 2024-12-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_item_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_name',
        ),
    ]
